{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-highlight
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/highlight_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/highlight/highlight_{{ version }}.tar.gz
  sha256: 0e8e5580e1c9301d3fa66af62b761d74f207bbb0b94116c1ebd1f3033cc90aea

build:
  merge_build_host: True  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('highlight')"           # [not win]
    - "\"%R%\" -e \"library('highlight')\""  # [win]

about:
  home: https://github.com/romainfrancois/highlight
  license: GPL-3.0-or-later
  summary: Syntax highlighter for R code based  on the results of the R parser. Rendering in
    HTML and latex  markup. Custom Sweave driver performing syntax highlighting  of
    R code chunks.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
