travis:
  secure:
    BINSTAR_TOKEN: p2pd6Fpx9Oc0ftE2wcq1rK1yTBRSXj6g7CXk73QsgenG1z0sM/ej4EKEL3PO+tjLh8LGwxwxzfP7gwoxY8EHZZIsl7MfsuRAoiPfnfrt1rVw3eymOD1izfZB1714QlqEu+aEBw0RYheasRXaUx0Wq/ekmJthq4Eayfkn4+UN2g+CA4slPitvig6R70AAREoqlKm1DiLQV8Jmp2r3IVA6hbtPL+tMS+Rb7iLtlDwMj9u+fkdQznWJaZY2ZbCJAEt7KopJ8JWzoo4I0d6SoX3T0kZN3fbL2/d1SSQFw59X0bs/QBB/6Jo6bhhSc46h4XAkkeiLxI1ALkJHQYBRZHNhViwU7WQJqBwJWcl0t4amcXbmTMGrK3tnXmFFPYyy3fz+k2QjorZ7vXrP/6UYikxvewagdDLdk3FiQOp9TsZBWmo8c/PQ+LHaDrRxT6IlHPcOcg2IW+cYz8+p9sMDnk1nxDu5P6Cjuh3lPlaKQ5aPcfOxd3mP6NO57AQ6fTJrV1zwK13AOemEoSGmrXnL9+d9mfWX3cU3dGdjGi4/yejO/4z3aPH0XzRi/BjpCE6eCfTucsEfcZkxR6NcWLwOBjon7PUvS9nt0xKi4oKNjKRvQq5O32B7pnSkHksHc8P6cDYsTBKd+aaE7J720fCSr8tnx1v5WdIVgdBdRvB+dCublQ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
