travis:
  secure:
    BINSTAR_TOKEN: ZT5NUYRMIKVwTdRMFd7nKHi1wq5AN6FUdfvm/uO8LrOmrnJy3C0/McsJmPs27do4K2e07lx2woX/NE2u+4NhABfb+44tWhdf9yl2JbsP+/X8EzvCPwvcq7Z/mUOCHOKlzOOmN4DqcCu15jap43otzZ0HX/YOzx7oD8fYbZCURRm3dxSNCBUdxJ64Y+LhQG3Ujku3vCg0s1BRLUu6bSosRdKJdvd087Wmn82UrnzwMrhLqavYlS+s3IF4b58eSz5+ur9gi+d5ptkR2EioCIFdBKZJyKQwP34AyBoH3eMFxclAk6cis/+HCjXMH2gNbSvWrSQc4Xh3WrYq1HXo1Pqh67Ddy4vSkp7U/cJHHQHFRJAQF3UjjI/gGsyZl/BnKa+k5dx6qNTwJPsi8sl4HPBLjeskZDRYvIEOeNpoXCY/XAvRgR7JzzvTlP6mEv0G5QwXpyZFCYQBmrzzmS4urBY8F949FXnrD125zIK3+xUk9cLi5bqHU45QSAY8AgSMxgNuqbGz3CSNbRxTaAxCK5QpE1oKDoKKFHBDBMDUEsxa/u5MNgKZSpN7vjgJyIvGGNcH8OZ5pUjLmDd9QgjOnekE82YXNRvhxZc5bChiylf0qHA2cRPyt8LDfQG4QKpUcW5GruTJ4j1ObX+pNJrI9942pTxpQP9mAekJbGvIVEZ6keg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
