appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: BGLUSH3jf7RJFzwuLMla08pZemsWHKSNLPk+bvaD26ikJWH8NZBX28QH4WVgbs3eC7EW3Wq2cHc+zhAgDwKAWDzwXWVXmYaD2QfgrN3dimfFxlX3pMSMgaJtHpVhfLcwIAqWIEamFkHnO3AjzIL1f+sa0k/u/oPdJnTg8k9wtmwg9eauALaQH058evSgnhtzadD3yERIdx7BkdPNJisg9hspDpyvOJ9abiAOUh/NCmAdPPQrS3NGd11bZbClcTj9NkxihdBZ0OJa3MBHYEMeStoS/q9cif0L93x0Lg9yI4BykqRSevMTd3KZAKuDEdHXtcJJgdfTXCuqU1+5fCWsJyaaeFrZ9dV5rfiFvF2z/99FPb0J2QeH92RNF7Jm6MlRL35AP+X+RKbU7YO/tbYMfULjPItZCghSoBU2ppUkMMV39g+AVOrDG95NoXCEtiLPIpC5ElATqAy2HTa78uqH2q1c3+yZQyqcHdho5TrUvGMJdvLhz9GcEmf9gUSsLaWOFOpAe6XYgQJgEAWxuNt5Wk3qnKbEMGOWigP1ouLNjuV+74EckF86jeqFlJkbaiNCZYhr4E4ZZsvdI3rucyMHb2ri7WuXyB8ncBbr+0VaGQWJcVFO6c8G0F2bo22P2oRt57QJiHktQ2h8sXHC0ctaAXSJtyrwkzXTiFGbbBcfza8=}
bot:
  automerge: true
